doctrine:
  dbal:
    driver: "pdo_pgsql"
    host: "%env(DB_HOST)%"
    port: "%env(int:DB_PORT)%"
    dbname: "%env(DB_NAME)%"
    user: "%env(DB_USER)%"
    password: "%env(DB_PASSWORD)%"
    charset: "utf8"
