version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: contacts_app
    working_dir: /var/www/html
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: contacts
      DB_USER: contacts
      DB_PASSWORD: contacts
    volumes:
      - .:/var/www/html
    ports:
      - "9000:9000"
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: contacts_db
    environment:
      POSTGRES_DB: contacts
      POSTGRES_USER: contacts
      POSTGRES_PASSWORD: contacts
    ports:
      - "55432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


